import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import bootstrap from "../../node_modules/bootstrap/dist/css/bootstrap.min.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="d-flex">
          <div id="content" className="flex-grow-1">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}


